# 敌方机器人增益

# 英雄
uint8  hero_heal
uint16 hero_cool
uint8  hero_def
uint8  hero_vuln
uint16 hero_atk

# 工程
uint8  engineer_heal
uint16 engineer_cool
uint8  engineer_def
uint8  engineer_vuln
uint16 engineer_atk

# 3 号步兵
uint8  infantry_3_heal
uint16 infantry_3_cool
uint8  infantry_3_def
uint8  infantry_3_vuln
uint16 infantry_3_atk

# 4 号步兵
uint8  infantry_4_heal
uint16 infantry_4_cool
uint8  infantry_4_def
uint8  infantry_4_vuln
uint16 infantry_4_atk

# 哨兵
uint8  sentry_heal
uint16 sentry_cool
uint8  sentry_def
uint8  sentry_vuln
uint16 sentry_atk
